site_name:  ""

theme:
  name: material
  features:
    - instant
    - tabs
  language: en
  logo: images/logo3.png
  favicon: images/logo.png
repo_name: DCC-EX/website
repo_url: https://github.com/DCC-EX/website
nav:
  - Home: 
    - About: 'index.md'
  - Getting Started:
    - Starter Kit: 'starter-kit.md'
    - Assembly: 'starter-kit.md'
    - Basic Setup: 'starter-kit.md'
    - Installer Setup: 'starter-kit.md'
    - Advanced Setup: 'starter-kit.md'
    - DCC++ EX & JMRI: 'starter-kit.md'
    - Rail Networking: 'starter-kit.md'
    - Automation: 'starter-kit.md'
  - Hardware:
    - Microcontrollers: 'power-supplies.md'
    - Motor Boards: 'power-supplies.md'
    - I2C Displays: 'power-supplies.md'
    - Power Supplies: 'power-supplies.md'
  - API:
    - Command Station: 'api.md'
  - Develop:
    - Base Station: 'da.md'
  - Tinker:
    - Contribute: 'tc.md'
  - Resources:
    - Resources: 'resources.md'
  - Downloads:
    - DCC++ Basestation: 'downloads.md'
    - Materials: 'downloads.md'
    
markdown_extensions: 
  - admonition
  - codehilite
extra_css:
  - stylesheets/extra.css