site_name: DCC++ EX

theme:
  name: material
  features:
    - instant
    - tabs
  language: en
  logo: images/logo.png
  favicon: images/logo.png
repo_name: DCC-EX/website
repo_url: https://github.com/DCC-EX/website
nav:
  - Home: 'index.md'
  - Getting Started:
    - Starter Kit: 'starter-kit.md'
    - Assembly: 'assembly.md'
  - Hardware:
    - Power Supplies: 'power-supplies.md'

markdown_extensions:
  - admonition
  - codehilite