site_name:  "DCC++ EX"

theme:
  name: material
  features:
    - tabs
    - instant
  language: en
  logo: images/new-logo.png
  favicon: images/new-logo.png

repo_name: DCC-EX/website
repo_url: https://github.com/DCC-EX/website

nav:
  - Home: 'index.md' 
  - Getting Started:
    - Choose your Path: 'start/levels.md'
    - Starter Kit: 'start/diy-starter-kit.md'
    - Hardware & Assembly: 'start/assembly.md'
    - Installer Setup: 'start/installer-setup.md'
    - Basic Setup: 'start/basic-setup.md'
  - Advanced Setup:
    - JMRI Setup: 'start/dccpp-jmri.md'
    - Rail Networking: 'start/rail-networking.md'
    - Automation: 'start/automation.md'
    - WIFI setup: 'start/wifi-setup.md'
  - Hardware:
    - Microcontrollers: 'hardware/microcontrollers.md'
    - Motor Boards: 'hardware/motor-boards.md'
    - I2C Displays: 'hardware/i2c-displays.md'
    - Power Supplies: 'hardware/power-supplies.md'
  - API:
    - Command Station: 'api/command-station-api.md'
  - Develop:
    - Base Station: 'develop/base-station-dev.md'
  - Tinker:
    - Tinker with DCC EX: 'tinker/tinkering.md'
  - Support:
    - How To Get Support: 'support/get-support.md'
  - Resources:
    - Resources: 'resources/resources.md'
  - Downloads:
    - DCC++ Basestation: 'download/dccex-downloads.md'
    - Materials: 'download/dccex-materials-downloads.md'
  - About:
    - Team: 'about/about-us.md'
    - What's New: 'notes/rewrite.md'
    
markdown_extensions: 
  - admonition
  - codehilite
  - attr_list
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js